"""Email notification client for sending incident summaries."""
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Any
from config import Config


class EmailClient:
    """Client for sending email notifications."""

    def __init__(self):
        self.recipient_email = Config.OPSGENIE_SLACK_EMAIL
        self.smtp_host = os.getenv("SMTP_HOST", "smtp.office365.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_user = os.getenv("SMTP_USER")
        self.smtp_password = os.getenv("SMTP_PASSWORD")
        self.sender_email = self.smtp_user or "noreply@newrelic-agent.local"

    def format_html_summary(
        self,
        incident_count: int,
        summary: str,
        insights: List[str],
        incidents: List[Dict[str, Any]]
    ) -> str:
        """
        Format incident summary as HTML email.

        Args:
            incident_count: Total number of incidents
            summary: AI-generated executive summary
            insights: List of key insights
            incidents: List of incident details

        Returns:
            HTML email body
        """
        # Priority colors
        priority_colors = {
            "CRITICAL": "#FF0000",
            "HIGH": "#FF6600",
            "MEDIUM": "#FFCC00",
            "LOW": "#00CC00"
        }

        # Build insights HTML
        insights_html = "".join([f"<li>{insight}</li>" for insight in insights])

        # Build incidents HTML (top 10)
        incidents_html = ""
        for incident in incidents[:10]:
            priority = incident.get("priority", "UNKNOWN")
            color = priority_colors.get(priority, "#999999")

            incidents_html += f"""
            <div style="margin: 10px 0; padding: 10px; border-left: 4px solid {color}; background: #f9f9f9;">
                <strong style="color: {color};">{priority}</strong> - {incident.get('title')}<br>
                <small>
                    ID: <code>{incident.get('incidentId')}</code> | 
                    Opened: {incident.get('openedAt')}
                </small>
            </div>
            """

        # Build full HTML email
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .header {{ background: #4A90E2; color: white; padding: 20px; text-align: center; }}
                .content {{ padding: 20px; }}
                .summary {{ background: #f0f7ff; padding: 15px; border-radius: 5px; margin: 15px 0; }}
                .insights {{ background: #fff3cd; padding: 15px; border-radius: 5px; margin: 15px 0; }}
                .footer {{ text-align: center; padding: 20px; color: #666; font-size: 12px; }}
                code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📊 New Relic Incidents Summary</h1>
            </div>
            
            <div class="content">
                <h2>Total Open Incidents: {incident_count}</h2>
                
                <div class="summary">
                    <h3>Executive Summary</h3>
                    <p>{summary}</p>
                </div>
                
                <div class="insights">
                    <h3>Key Insights & Recommendations</h3>
                    <ul>
                        {insights_html}
                    </ul>
                </div>
                
                <h3>Top Incidents (showing {min(10, len(incidents))} of {len(incidents)})</h3>
                {incidents_html}
            </div>
            
            <div class="footer">
                <p>Generated by New Relic Incident Summary Agent</p>
                <p>Powered by IBM WatsonX Granite AI</p>
            </div>
        </body>
        </html>
        """

        return html

    def format_text_summary(
        self,
        incident_count: int,
        summary: str,
        insights: List[str],
        incidents: List[Dict[str, Any]]
    ) -> str:
        """
        Format incident summary as plain text email.

        Args:
            incident_count: Total number of incidents
            summary: AI-generated executive summary
            insights: List of key insights
            incidents: List of incident details

        Returns:
            Plain text email body
        """
        text = f"""
NEW RELIC INCIDENTS SUMMARY
{'='*60}

Total Open Incidents: {incident_count}

EXECUTIVE SUMMARY
{'-'*60}
{summary}

KEY INSIGHTS & RECOMMENDATIONS
{'-'*60}
"""
        for insight in insights:
            text += f"• {insight}\n"

        text += f"\n\nTOP INCIDENTS (showing {min(10, len(incidents))} of {len(incidents)})\n"
        text += f"{'-'*60}\n"

        for i, incident in enumerate(incidents[:10], 1):
            priority_emoji = {
                "CRITICAL": "🔴",
                "HIGH": "🟠",
                "MEDIUM": "🟡",
                "LOW": "🟢"
            }.get(incident.get("priority"), "⚪")

            text += f"\n{i}. {priority_emoji} {incident.get('title')}\n"
            text += f"   Priority: {incident.get('priority')}\n"
            text += f"   ID: {incident.get('incidentId')}\n"
            text += f"   Opened: {incident.get('openedAt')}\n"

        text += f"\n{'-'*60}\n"
        text += "Generated by New Relic Incident Summary Agent\n"
        text += "Powered by IBM WatsonX Granite AI\n"

        return text

    def send_summary_email(
        self,
        incident_count: int,
        summary: str,
        insights: List[str],
        incidents: List[Dict[str, Any]]
    ) -> bool:
        """
        Send incident summary via email to Slack/Opsgenie.

        Args:
            incident_count: Total number of incidents
            summary: AI-generated executive summary
            insights: List of key insights
            incidents: List of incident details

        Returns:
            True if successful, False otherwise
        """
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"📊 New Relic Incidents Summary - {incident_count} Open Issues"
            msg['From'] = self.sender_email
            msg['To'] = self.recipient_email

            # Create plain text and HTML versions
            text_content = self.format_text_summary(incident_count, summary, insights, incidents)
            html_content = self.format_html_summary(incident_count, summary, insights, incidents)

            # Attach both versions
            part1 = MIMEText(text_content, 'plain')
            part2 = MIMEText(html_content, 'html')
            msg.attach(part1)
            msg.attach(part2)

            # Check if SMTP is configured
            if not self.smtp_user or not self.smtp_password:
                print(f"⚠️  SMTP credentials not configured")
                print(f"📧 Would send email to: {self.recipient_email}")
                print(f"\nEmail Preview:\n")
                print(text_content)
                return True  # Consider it successful for demo purposes

            # Send via SMTP
            try:
                print(f"📧 Connecting to {self.smtp_host}:{self.smtp_port}...")
                with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                    server.starttls()
                    print(f"🔐 Authenticating as {self.smtp_user}...")
                    server.login(self.smtp_user, self.smtp_password)
                    print(f"📤 Sending email to {self.recipient_email}...")
                    server.send_message(msg)
                print(f"✅ Email sent successfully to {self.recipient_email}")
                return True
            except smtplib.SMTPAuthenticationError as auth_error:
                print(f"❌ SMTP Authentication failed: {auth_error}")
                print(f"💡 Check your SMTP_USER and SMTP_PASSWORD in .env file")
                print(f"💡 If using MFA, you may need an app password")
                return False
            except smtplib.SMTPException as smtp_error:
                print(f"❌ SMTP error: {smtp_error}")
                return False
            except Exception as conn_error:
                print(f"❌ Connection error: {conn_error}")
                print(f"\n📧 Email Preview (not sent):\n")
                print(text_content)
                return False

        except Exception as e:
            print(f"❌ Failed to send email: {str(e)}")
            return False

    def send_simple_notification(self, message: str) -> bool:
        """
        Send a simple text notification.

        Args:
            message: Simple text message

        Returns:
            True if successful
        """
        print(f"📧 Notification to {self.recipient_email}:")
        print(message)
        return True

